name: tatyassar
description: Tatyassar — Intelligent Decision Support System for stress management through personalized therapeutic interventions.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Utilities
  http: ^1.2.1
  intl: ^0.20.2
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.1.0
  connectivity_plus: ^6.0.3
  lottie: ^3.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.11
  firebase_storage: ^12.4.9
  google_sign_in: ^6.2.1
  shimmer: ^2.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/images/on_boarding_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
