// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDApH_DLd45GSAuHF_Kf1xMZpLhlD_XU4w',
    appId: '1:518508507331:web:7cd183fbe747369130f276',
    messagingSenderId: '518508507331',
    projectId: 'leanfix-store',
    authDomain: 'leanfix-store.firebaseapp.com',
    storageBucket: 'leanfix-store.firebasestorage.app',
    measurementId: 'G-2WNHXKCP0M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7T1DQwFQHgteIg7LpnMpvqF1jvGv4m0o',
    appId: '1:518508507331:android:5e49b005f267934630f276',
    messagingSenderId: '518508507331',
    projectId: 'leanfix-store',
    storageBucket: 'leanfix-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIO7cAXBNh6ttVef3tZzVLE3wHAoZ8HjQ',
    appId: '1:518508507331:ios:9de6a5aa29c9e02430f276',
    messagingSenderId: '518508507331',
    projectId: 'leanfix-store',
    storageBucket: 'leanfix-store.firebasestorage.app',
    androidClientId: '518508507331-ccorlnst3lldnegmaedprs0bvpd0d60c.apps.googleusercontent.com',
    iosClientId: '518508507331-tmpadmelrod7s0l9qrq24c0m34hsi5nc.apps.googleusercontent.com',
    iosBundleId: 'com.nawaffahad.LeanFixStore',
  );

}