// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOlL9jrM88MPsltU4Qc_wuGkrMIg2MSzU',
    appId: '1:654246235466:web:1c697f1e85e2e431bdc5b3',
    messagingSenderId: '654246235466',
    projectId: 'umbrella-c5dab',
    authDomain: 'umbrella-c5dab.firebaseapp.com',
    storageBucket: 'umbrella-c5dab.firebasestorage.app',
    measurementId: 'G-2XN8RC02BT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy0Sle8H2INMIHsdtXQCwEWNeJ2A5ZUHo',
    appId: '1:654246235466:android:20650160fde5a668bdc5b3',
    messagingSenderId: '654246235466',
    projectId: 'umbrella-c5dab',
    storageBucket: 'umbrella-c5dab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIbWovbdywQuhgoNoGOoITMur5g-yKWeM',
    appId: '1:654246235466:ios:967795cc6d421f52bdc5b3',
    messagingSenderId: '654246235466',
    projectId: 'umbrella-c5dab',
    storageBucket: 'umbrella-c5dab.firebasestorage.app',
    iosClientId: '654246235466-ct6gbfngladf55tqektkpe76a6n9fvpv.apps.googleusercontent.com',
    iosBundleId: 'com.nawaf.Tatyassar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIbWovbdywQuhgoNoGOoITMur5g-yKWeM',
    appId: '1:654246235466:ios:883060890a4ea1cfbdc5b3',
    messagingSenderId: '654246235466',
    projectId: 'umbrella-c5dab',
    storageBucket: 'umbrella-c5dab.firebasestorage.app',
    iosClientId: '654246235466-94e0vh4s3aun1da3kcj6684vsteb5eb1.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}